### ISSUE TITLE
加拿大detail数据未完全抓取就录入

### ISSUE THREAD

**Issue by guowenjia** [masschaos/lottocrawler#14]
https://cac.lottowawa.com/lotteries/ca-pick-4/results?after=20200617000000&before=  这里的detail数据缺失了。网站的某个数据还没更新的情况下，是不能向服务器推送的，得所有该有的字段都完整才能推送。这个是目前遇到的一个，麻烦也检查一下加拿大其他彩种是否也有类似问题。

**Comment by hyacinthus** [comment]
closed by #17
