### ISSUE TITLE
美国开奖数据抓取

### ISSUE THREAD

**Issue by guowenjia** [masschaos/lottocrawler#23]
美国的6个彩票的最新结果爬虫及历史数据结果。

开奖结果的地址在这里： https://www.calottery.com/draw-games

项目的 README 你需要看一下，遵守其中描述的规则。

目标网站有能返回 json 的公开 API 可以调用，直接用 axios 调用 API 即可

项目里其他国家的代码你不用参考，因为都不是专门搞 nodejs 的人写的，我们选择你的原因也是希望你能带来优雅规范的 nodejs 代码。

你的爬虫需要返回一个规定的 Object，结构在美国的国家文件夹中有样例。./lottocrawler/crawler/us/ca/example。

**Comment by hyacinthus** [comment]
测试中

**Comment by guowenjia** [comment]
目前发现了三个问题。
1.数据没按给的样例去存。存入数据只要一个对象，你在外边包了一层，给了个列表。
2.时间不对(drawTime)，我是按开奖时间给的用例，对应的hour,minute,second 只需要根据我给的时间去拼接就可以。需要注意里面有一天开两次的情况，我跑了一下你的代码，所有的时间都是070000.
3.daily3,daily4的numbers没按我给的格式存，我是用的|，你用的逗号。
