### ISSUE TITLE
日本彩票爬虫抓取

### ISSUE THREAD

**Issue by guowenjia** [masschaos/lottocrawler#28]
日本的7个彩票的最新结果爬虫。

开奖结果的地址在这里： https://www.takarakuji-official.jp/check/?__ope=%E5%BD%93%E3%81%9B%E3%82%93%E7%B5%90%E6%9E%9C%E3%81%AE%E3%81%94%E6%A1%88%E5%86%85&__fromScreenId=SC_WMK_SP_011

项目的 README 你需要看一下，遵守其中描述的规则。

目标网站如果有能返回 json 的公开 API 可以调用，直接用 axios 调用 API 即可，如果没有，使用puppeteer进行抓取。
![image](https://user-images.githubusercontent.com/27345371/89396744-83110c00-d741-11ea-88be-29e668c9a439.png)

你的爬虫需要返回一个规定的 Object，结构在日本的国家文件夹中有样例。./lottocrawler/crawler/jp/example。

**Comment by hyacinthus** [comment]
修正，这个任务只要最新结果，不用历史结果。
