### ISSUE TITLE
澳大利亚需要改善的问题

### ISSUE THREAD

**Issue by hyacinthus** [masschaos/lottocrawler#3]
- [x] 目录结构中应该有国家文件夹，不然某个文件夹如果平铺所有国家的文件将会过多。国家文件夹用小写两位国家代码。
- [x] 可配置的参数，我们都用环境变量。读取 process.env 即可。
- [x] 调用我们自己的接口，由于分布在不同的地方，你可以在一个地方定义一个 axios 的 instance ，把 baseurl 和 认证信息 预定义进去。用的时候就只用 post("results") 这样写相对链接就行了。
- [x] 调度目标1：保存数据时尽量不出现 重复记录 这个错误。我们可以请求 get("results?country=au&level=0") 把当前最新结果和彩种信息里的预期开奖时间对比计算出需不需要拉数据。
- [x] 调度目标2：尽可能少的爬源，降低被封概率。上一条如果做到了，没有新结果的就不需要拉。需要拉的时候10分钟检查一次吧。后面我还有个办法减少爬的概率，下一期任务再做那个改善吧。
- [ ] 由于爬虫其实是很不稳定的，随时有可能被封，所以我们要能检查出来各种失败的情况。
- [ ] 捕获所有的异常，尽可能的处理可预期的异常，把它翻译成人能看懂的错误。
- [ ] 我们的通知库就绪了 https://www.npmjs.com/package/@masschaos/im  用它给我们slack发通知，每爬一次产生一条通知：如果我们认为该出结果了但是还没出，发 debug ，如果爬成功了，发info，发生了其他的错误，发error 。
- [ ] 发消息频道可以写死，im.setChannels('dev', '业务通知', '出错通知')  token需要用环境变量传进去，我完了给你token用作调试。

**Comment by hyacinthus** [comment]
继续提一些问题

- [ ] 不用自己解析 crontab 表达式，其实还挺麻烦的，你解析的有问题。找个 cron parser 的库就好每个语言肯定都有。
- [ ] 判断需要抓一个彩种时，如果主源没得到结果，再去检查备用源，如果得到了，就不要再去抓备用源了。

**Comment by lynnroyal** [comment]
恩，了解，我晚上改进一下





------------------ 原始邮件 ------------------
发件人: 王瑞华 <notifications@github.com&gt;
发送时间: 2020年7月8日 16:15
收件人: masschaos/lottocrawler <lottocrawler@noreply.github.com&gt;
抄送: lin yan <cnblogs@vip.qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[masschaos/lottocrawler] 澳大利亚需要改善的问题 (#3)





 
继续提一些问题
  
 不用自己解析 crontab 表达式，其实还挺麻烦的，你解析的有问题。找个 cron parser 的库就好每个语言肯定都有。 

 判断需要抓一个彩种时，如果主源没得到结果，再去检查备用源，如果得到了，就不要再去抓备用源了。

**Comment by hyacinthus** [comment]
更新： 通知库 im 不用你集成了，我需要完善一下你的调度过程，顺便就加上了。
这个任务列表里就只剩下识别爬虫错误了。要能报告出是网络问题还是源站结构改了等等不同情况。

**Comment by lynnroyal** [comment]
好的，有时间我加一下





------------------ 原始邮件 ------------------
发件人: 王瑞华 <notifications@github.com&gt;
发送时间: 2020年7月13日 16:38
收件人: masschaos/lottocrawler <lottocrawler@noreply.github.com&gt;
抄送: lin yan <cnblogs@vip.qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[masschaos/lottocrawler] 澳大利亚需要改善的问题 (#3)





 
更新： 通知库 im 不用你集成了，我需要完善一下你的调度过程，顺便就加上了。
 这个任务列表里就只剩下识别爬虫错误了。要能报告出是网络问题还是源站结构改了等等不同情况。

**Comment by hyacinthus** [comment]
放弃此任务
