### ISSUE TITLE
韩国最新数据抓取

### ISSUE THREAD

**Issue by guowenjia** [masschaos/lottocrawler#39]
开奖地址在  
https://dhlottery.co.kr/gameResult.do?method=byWin
https://dhlottery.co.kr/gameResult.do?method=win720
总共两个彩种
爬虫需要返回一个规定的 Object，结构在法国的国家文件夹中有样例。./lottocrawler/crawler/kr/example。

**Comment by mapleincode** [comment]
https://github.com/masschaos/lottocrawler/pull/41
