### ISSUE TITLE
巴西最新数据及历史数据抓取

### ISSUE THREAD

**Issue by guowenjia** [masschaos/lottocrawler#52]
总共8个彩种

爬虫需要返回一个规定的 Object，结构在巴西的国家文件夹中有样例。./lottocrawler/crawler/br/example。drawTime确保按照example里面的readme.md来处理。开奖地址也在readme.md里面。

**Comment by mapleincode** [comment]
收到

**Comment by mapleincode** [comment]
https://github.com/masschaos/lottocrawler/pull/58
